- name: install webservice
  package: 
   name: httpd
   state: present

- name: Copy studentapp configaration
  copy:
   src: studentapp.config
   dest: /etc/httpd/conf.d/studentapp.conf

- name: Download deafult index file 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
    dest: /var/www/html/index.html

- name: Restart service httpd, in all cases
  service:
    name: httpd
    state: restarted
    enabled: yes 
